---
- name: installing packages
  hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: installed

  - name: starting httpd services
    service:
      name: httpd
      state: started
  - copy:
      src: /home/vivek/playbooks/index.html
      dest: /var/www/html
